"""empty message

Revision ID: 4ae224c354ce
Revises: 0eb52b6d9345
Create Date: 2025-12-07 22:05:27.559012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae224c354ce'
down_revision = '0eb52b6d9345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_sailor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_captain', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_sailor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_captain')

    # ### end Alembic commands ###
