"""empty message

Revision ID: 6592cefc808c
Revises: 
Create Date: 2025-12-15 13:33:36.904162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6592cefc808c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sailor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sailor_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_ocean_god', sa.Boolean(), nullable=False),
    sa.Column('profile_photo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sailor_name')
    )
    op.create_table('claude_mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=245), nullable=False),
    sa.Column('objective', sa.String(length=120), nullable=False),
    sa.Column('scrolls', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['sailor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['sailor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('is_crew', sa.Boolean(), nullable=False),
    sa.Column('sailor_id', sa.Integer(), nullable=True),
    sa.Column('crew_id', sa.Integer(), nullable=True),
    sa.Column('claude_mission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claude_mission_id'], ['claude_mission.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_sailor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sailor_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'KICKED', name='crew_sailor_status'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=245), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('sailor_owner_id', sa.Integer(), nullable=True),
    sa.Column('crew_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['sailor.id'], ),
    sa.ForeignKeyConstraint(['crew_owner_id'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['sailor_owner_id'], ['sailor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('is_crew', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['sailor.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objective')
    op.drop_table('mission')
    op.drop_table('crew_sailor')
    op.drop_table('contribution')
    op.drop_table('crew')
    op.drop_table('claude_mission')
    op.drop_table('sailor')
    # ### end Alembic commands ###
