"""empty message

Revision ID: f9e036bfbfc9
Revises: 0290f65a9ba3
Create Date: 2025-12-07 18:34:49.895506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9e036bfbfc9'
down_revision = '0290f65a9ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_sailor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))

    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('completed_ad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('crew_sailor', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
